alter table if exists news
    drop constraint if exists FKse4kp8hpul3sks7iofw87xor6;
alter table if exists tag_news
    drop constraint if exists FKqw54xwh1h7ietbo4hvqsryu5v;
alter table if exists tag_news
    drop constraint if exists FKbfnhl1q34pwo0cchjwjq1muq;
drop table if exists authors cascade;
drop table if exists news cascade;
drop table if exists tag_news cascade;
drop table if exists tags cascade;
create table authors
(
    id               int8 generated by default as identity,
    create_date      timestamp,
    last_update_date timestamp,
    name             varchar(255),
    primary key (id)
);
create table news
(
    id             int8 generated by default as identity,
    content        varchar(255),
    createDate     timestamp,
    lastUpdateDate timestamp,
    title          varchar(255),
    author_id      int8,
    primary key (id)
);
create table tag_news
(
    tag_id  int8 not null,
    news_id int8 not null
);
create table tags
(
    id int8 generated by default as identity,
    name        varchar(255),
    primary key (id)
);
alter table if exists news
    add constraint FKse4kp8hpul3sks7iofw87xor6 foreign key (author_id) references authors;
alter table if exists tag_news
    add constraint FKqw54xwh1h7ietbo4hvqsryu5v foreign key (news_id) references news;
alter table if exists tag_news
    add constraint FKbfnhl1q34pwo0cchjwjq1muq foreign key (tag_id) references tags;